backend:
  name: git-gateway
  branch: feat/cms-faq
  # need to change to master later

local_backend: true

publish_mode: editorial_workflow

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - label: "FAQ Page"
    name: "faq-page"
    files:
      - label: "FAQ"
        name: "faq"
        file: "cms/faq-page/faq.json"
        format: "json"
        editor:
          preview: true
        fields:
          - { label: "Title", name: "title", widget: "string", hint: "This is used for the page title" }
          - { label: "Body", name: "body", widget: "markdown", hint: "This is the body text." }
